const FIREBASE_CONFIG={apiKey:"AIzaSyCQHQVC5dtAqgrrNo19_5JUH7t7dV1qXx0",authDomain:"atividades-douglas.firebaseapp.com",databaseURL:"https://atividades-douglas-default-rtdb.firebaseio.com",projectId:"atividades-douglas",storageBucket:"atividades-douglas.firebasestorage.app",messagingSenderId:"546897428823",appId:"1:546897428823:web:250438dd79a300b7b4be12"};
const GAME_ID="museu-das-independencias",GAME_TITLE="Museu das Independências",DB_ROOT="estacao_aprendizagem",A="assets/";
let db=null;try{if(!firebase.apps.length)firebase.initializeApp(FIREBASE_CONFIG);db=firebase.database()}catch(error){console.warn("Firebase indisponível",error)}
const q=(text,ops,ok,exp)=>({text,ops,ok,exp});
const GALLERIES=[
{id:"processo",title:"Muito além do 7 de Setembro",short:"Processo longo",intro:"De 1808 ao reconhecimento português: causas, agentes, interesses e permanências.",accent:"#8a3440",cover:A+"leopoldina-bonifacio.png",pages:[
{t:"Uma ruptura em processo",img:A+"medalha-joao-vi.png",cap:"Medalha da aclamação de D. João VI, 1818. A presença da Corte no Rio alterou o lugar político do Brasil.",text:"A Independência não começou nem terminou em 7 de setembro de 1822. A transferência da Corte em 1808, a abertura dos portos, o Reino Unido, a Revolução do Porto, o Dia do Fico, as articulações de Leopoldina e José Bonifácio, as guerras e o reconhecimento português em 1825 compõem um processo longo.",concepts:[["Interiorização da metrópole","Maria Odila Dias destacou o fortalecimento do centro político português instalado no Rio."],["Emancipação política","Separação formal de Portugal sem ruptura completa das estruturas sociais."],["Permanência","Monarquia, escravidão e poder das elites atravessaram a separação."]],exam:"Questões de prova costumam opor “ato isolado” a “processo histórico”. Prefira explicações que relacionem diferentes momentos e interesses.",trap:"Independência política não significou independência econômica, igualdade social ou fim imediato dos vínculos portugueses."},
{t:"Agentes e interesses",img:A+"leopoldina-bonifacio.png",cap:"Maria Leopoldina e José Bonifácio participaram das articulações políticas que levaram à separação.",text:"D. Pedro tornou-se o principal símbolo, mas decisões e negociações envolveram Leopoldina, José Bonifácio, comerciantes, proprietários, militares, grupos populares e interesses britânicos. As elites buscavam autonomia sem destruir a ordem escravista.",concepts:[["Partido Brasileiro","Articulou interesses de grupos estabelecidos no Brasil."],["Inglaterra","Mediou o reconhecimento e ampliou sua influência econômica."],["Elite escravista","Apoiou mudanças políticas que preservassem propriedade e hierarquia."]]},
{t:"Uma América em transformação",img:A+"mapa-america.png",cap:"Independências na América Latina no século XIX.",text:"O processo brasileiro integrou a crise do colonialismo e das monarquias ibéricas, influenciada pelo Iluminismo, pelas revoluções atlânticas e pelas guerras napoleônicas. O caso brasileiro, porém, preservou a monarquia e a unidade territorial sob um príncipe da dinastia portuguesa.",concepts:[["Contexto atlântico","As independências fizeram parte de uma transformação internacional."],["Singularidade brasileira","Monarquia, unidade territorial e continuidade dinástica."]]}],
questions:[
q("A interpretação atualmente mais aceita sobre a Independência do Brasil afirma que ela foi:",["um processo longo, com diferentes agentes, conflitos e negociações","um ato concluído exclusivamente no Ipiranga","uma ruptura social que aboliu a escravidão","uma decisão tomada apenas pela Inglaterra"],0,"O 7 de Setembro é um marco simbólico dentro de um processo mais amplo."),
q("O conceito de “interiorização da metrópole” relaciona-se:",["ao fortalecimento do centro político português instalado no Rio de Janeiro","à expulsão imediata de todos os portugueses","à transferência da capital para o interior","ao fim da monarquia em 1808"],0,"A Corte criou no Rio um novo centro de poder, com interesses próprios."),
q("Uma importante permanência após 1822 foi:",["a manutenção da escravidão e do poder das elites proprietárias","a recolonização oficial por Portugal","o sufrágio universal","a implantação da República"],0,"A emancipação política não alterou imediatamente a estrutura escravista."),
q("A atuação britânica no reconhecimento da Independência revela:",["a inserção do processo em relações diplomáticas e econômicas internacionais","a ausência de interesses comerciais europeus","o isolamento completo do novo país","a anexação do Brasil pela Inglaterra"],0,"A mediação britânica esteve ligada à sua influência econômica."),
q("Leopoldina e José Bonifácio aparecem na historiografia porque:",["participaram de decisões e articulações políticas da separação","comandaram juntos a Batalha do Jenipapo","redigiram a Constituição de 1891","defenderam o retorno colonial"],0,"A Independência não resultou da ação de um único personagem."),
q("Comparado a muitos processos hispano-americanos, o Brasil preservou:",["a monarquia e a unidade territorial sob a dinastia de Bragança","o domínio colonial direto até 1889","a divisão em várias repúblicas","a abolição imediata da escravidão"],0,"A continuidade monárquica foi uma característica marcante.")
]},
{id:"guerras",title:"Independências em guerra",short:"Lutas regionais",intro:"Bahia, Piauí, Maranhão e Pará: conflitos que consolidaram o novo território.",accent:"#9a4a2e",cover:A+"batalha-jenipapo.jpg",pages:[
{t:"O território não aderiu de uma vez",img:A+"batalha-jenipapo.jpg",cap:"Batalha do Jenipapo, representação presente no material didático. O conflito ocorreu no Piauí em 13 de março de 1823.",text:"Tropas portuguesas resistiram em diferentes províncias. No Piauí, combatentes de várias regiões enfrentaram as forças de Cunha Fidié. Na Bahia, a guerra prosseguiu até 2 de julho de 1823. Maranhão e Grão-Pará também aderiram depois de pressões e conflitos.",concepts:[["Independências no plural","As experiências regionais tiveram ritmos, agentes e conflitos próprios."],["Consolidação territorial","A separação proclamada precisava ser efetivada militarmente."],["Participação popular","Pobres, libertos, escravizados, indígenas e mulheres atuaram nos conflitos."]],exam:"A existência de guerras regionais enfraquece a narrativa de uma Independência pacífica e concedida apenas pelas elites.",trap:"Não confunda a declaração de 1822 com a adesão imediata de todas as províncias."},
{t:"A guerra na Bahia",img:A+"joana-angelica.jpg",cap:"Joana Angélica foi morta ao tentar impedir a entrada de soldados portugueses no Convento da Lapa, em 1822.",text:"A resistência baiana cercou as forças de Madeira de Melo. A Batalha de Pirajá e a mobilização do Recôncavo contribuíram para a expulsão das tropas portuguesas em 2 de julho de 1823.",concepts:[["Joana Angélica","Símbolo da resistência à invasão portuguesa em Salvador."],["2 de Julho","Marca a expulsão das tropas portuguesas da Bahia."],["Pirajá","Batalha decisiva no cerco a Salvador."]]},
{t:"Protagonistas silenciadas",img:A+"maria-quiteria.jpg",cap:"Maria Quitéria de Jesus, combatente das forças brasileiras na guerra da Bahia.",text:"Maria Quitéria alistou-se disfarçada e combateu; Maria Felipa liderou ações contra embarcações portuguesas; Leopoldina articulou decisões e recursos. Essas trajetórias questionam narrativas exclusivamente masculinas e palacianas.",concepts:[["Maria Quitéria","Participação militar reconhecida e condecorada."],["Maria Felipa","Liderança popular negra na Ilha de Itaparica."],["Leopoldina","Atuação política, diplomática e material."]],exam:"Em questões sobre protagonismo, relacione a personagem à forma concreta de sua participação."}],
questions:[
q("As lutas na Bahia, Piauí, Maranhão e Pará demonstram que:",["a Independência precisou ser consolidada por conflitos regionais","todas as províncias aderiram imediatamente em 1822","somente a elite do Rio participou","não existiam tropas portuguesas no Brasil"],0,"A adesão ao novo Império foi desigual e frequentemente violenta."),
q("O 2 de Julho de 1823 é importante porque marca:",["a expulsão das tropas portuguesas da Bahia","a coroação de D. Pedro I","a dissolução da Constituinte","o reconhecimento português da Independência"],0,"A data simboliza a consolidação da Independência na Bahia."),
q("A Batalha do Jenipapo evidencia:",["a participação de setores populares na luta pela Independência","a ausência de combates no Piauí","a vitória portuguesa definitiva","uma guerra contra a Inglaterra"],0,"Combatentes piauienses, cearenses, maranhenses e baianos enfrentaram Cunha Fidié."),
q("Maria Quitéria destacou-se por:",["combater nas forças brasileiras durante a guerra na Bahia","redigir a Constituição de 1824","liderar a Assembleia Constituinte","negociar o reconhecimento em Londres"],0,"Sua trajetória amplia o conjunto de protagonistas da Independência."),
q("Maria Felipa é associada:",["à mobilização de mulheres contra embarcações portuguesas em Itaparica","à pintura do Grito do Ipiranga","ao Poder Moderador","à Revolução do Porto"],0,"Ela representa a participação popular negra e feminina no conflito baiano."),
q("A expressão “Independências” no plural procura destacar:",["a diversidade regional e social do processo","a existência de vários países dentro do Brasil","a ausência de um governo central","a repetição anual do 7 de Setembro"],0,"O plural valoriza ritmos e experiências distintas.")
]},
{id:"memoria",title:"A imagem que virou História",short:"Arte e memória",intro:"Compare Pedro Américo e Moreaux e descubra como pinturas fabricam memória nacional.",accent:"#315e6d",cover:A+"independencia-morte.jpg",pages:[
{t:"Pedro Américo: heroísmo",img:A+"independencia-morte.jpg",cap:"Independência ou Morte!, Pedro Américo, 1888. Museu Paulista da USP.",text:"A obra foi concluída 66 anos após o acontecimento e encomendada no Segundo Reinado. D. Pedro aparece no centro, em cavalo imponente, cercado por uma guarda uniformizada. O povo ocupa as margens e observa.",concepts:[["Anacronismo","Uniformes representados foram criados depois de 1822; a Casa do Grito é posterior."],["Centralidade","Composição transforma D. Pedro no herói fundador."],["Memória oficial","A pintura ajudou a fixar uma versão militar e grandiosa."]],exam:"Uma pintura histórica pode informar mais sobre a época em que foi produzida do que sobre a aparência exata do acontecimento.",trap:"Não trate a obra como registro fotográfico do 7 de Setembro."},
{t:"Moreaux: aclamação",img:A+"proclamacao-moreaux.jpg",cap:"A Proclamação da Independência, François-René Moreaux, 1844.",text:"Moreaux representa D. Pedro saudando uma multidão que participa da comemoração. Soldados aparecem ao fundo e o clima é pacífico. A população, porém, tem traços e roupas europeizados, enquanto indígenas e negros são quase apagados.",concepts:[["Aclamação","O imperador é apresentado como amado pelo povo."],["Idealização","A multidão não corresponde à diversidade da sociedade brasileira."],["Encomenda","A obra foi criada a pedido do Senado Imperial."]]},
{t:"Compare para interpretar",img:A+"charge-produto-ingles.png",cap:"Charge contemporânea ironizando o caráter elitista e a dependência inglesa após a Independência.",text:"Fontes visuais possuem linguagem, autoria e intenção. Pedro Américo privilegia o gesto militar; Moreaux constrói uma aclamação popular idealizada; a charge questiona quem realmente se beneficiou e a dependência econômica britânica.",concepts:[["Representação","Imagem produz uma narrativa, não apenas copia a realidade."],["Silenciamento","Negros, indígenas e conflitos regionais foram minimizados."],["Contraponto","Comparar fontes revela escolhas e disputas de memória."]],exam:"Observe quem está no centro, quem aparece nas margens e quais gestos organizam a cena."}],
questions:[
q("A pintura Independência ou Morte!, de Pedro Américo, foi produzida:",["em 1888, décadas depois do acontecimento","no próprio dia 7 de setembro de 1822","durante a Constituinte de 1823","após a Proclamação da República"],0,"A distância temporal é essencial para analisar a construção de memória."),
q("Na obra de Pedro Américo, o povo aparece principalmente:",["como observador periférico do gesto heroico de D. Pedro","comandando militarmente a cena","ocupando o centro da composição","representado de maneira socialmente diversa"],0,"O imperador e sua guarda dominam a narrativa visual."),
q("Moreaux diferencia-se de Pedro Américo ao:",["representar uma aclamação civil e aparentemente popular","eliminar D. Pedro da cena","retratar apenas batalhas regionais","denunciar explicitamente a escravidão"],0,"A multidão participa da celebração, ainda que idealizada."),
q("Os uniformes posteriores a 1822 e a Casa do Grito construída depois são exemplos de:",["anacronismos na pintura de Pedro Américo","provas fotográficas do acontecimento","elementos presentes no relato de D. Pedro","símbolos republicanos"],0,"São elementos deslocados no tempo, escolhidos para construir a cena."),
q("Ao comparar as duas pinturas, conclui-se que:",["cada artista construiu uma narrativa de acordo com seu contexto e encomenda","ambas reproduziram exatamente o acontecimento","a arte não participa da memória política","as obras foram produzidas pelo mesmo autor"],0,"Representações históricas são escolhas estéticas e políticas."),
q("A pouca presença de negros e indígenas nas obras revela:",["um silenciamento da diversidade social na memória oficial","a inexistência desses grupos no Brasil","a participação política igualitária","o fim da escravidão em 1822"],0,"Ausências visuais também são evidências históricas.")
]},
{id:"constituinte",title:"A Constituição que não chegou",short:"Constituinte de 1823",intro:"Projetos de poder, participação restrita e a Noite da Agonia.",accent:"#76522d",cover:A+"camara-deputados.jpg",pages:[
{t:"Organizar o novo Império",img:A+"decreto-constituinte.png",cap:"Decreto de 3 de junho de 1822 autorizando a convocação de uma Assembleia Constituinte.",text:"O novo país precisava definir instituições e limites do governo. A Assembleia instalada em maio de 1823 reuniu deputados provinciais e discutiu uma monarquia constitucional, enquanto guerras de Independência ainda ocorriam.",concepts:[["Constituição","Lei fundamental que organiza poderes e direitos."],["Representação restrita","A participação direta concentrou-se nas elites, embora petições populares circulassem."],["Conflito central","Deputados desejavam limitar o imperador; D. Pedro defendia ampla autoridade."]],exam:"Diferencie liberalismo político de democracia social: muitos deputados defendiam limites ao monarca sem questionar a escravidão.",trap:"A Constituinte não foi eleita por sufrágio universal."},
{t:"A Assembleia",img:A+"camara-deputados.jpg",cap:"Representação da Câmara dos Deputados reunida no edifício da Cadeia Velha.",text:"Liberais moderados pretendiam consolidar a emancipação preservando a ordem social; exaltados defendiam reformas mais amplas. Portugueses ligados ao comércio e à Corte também disputavam o futuro do Império.",concepts:[["Moderados","Limites ao imperador e preservação da ordem social."],["Exaltados","Sufrágio mais amplo, separação Igreja-Estado e, para alguns, República."],["Projeto constitucional","O texto ficou associado à exigência de renda e ao predomínio dos proprietários."]]},
{t:"Noite da Agonia",img:A+"noite-agonia.png",cap:"Representação das tropas que cercaram a Assembleia Constituinte em novembro de 1823.",text:"Em 11 e 12 de novembro, tropas cercaram a Assembleia. D. Pedro dissolveu a Constituinte, prendeu deputados e exilou opositores. Um Conselho de Estado escolhido pelo imperador redigiu outro texto.",concepts:[["Dissolução","Interrupção militar do trabalho constituinte."],["Autoritarismo","O imperador recusou limites considerados excessivos."],["Outorga","A Constituição seguinte seria concedida pelo governante, não aprovada pela Assembleia."]],exam:"Associe a Noite da Agonia ao conflito entre representação legislativa e concentração de poder monárquico."}],
questions:[
q("O principal conflito da Constituinte de 1823 envolvia:",["os limites do poder de D. Pedro I diante do Legislativo","a escolha entre monarquia e domínio espanhol","a abolição imediata já aceita pelas elites","a transferência da capital para Salvador"],0,"Deputados buscavam limitar o monarca, que resistia a essas restrições."),
q("A participação política na Constituinte foi:",["restrita às elites, embora petições expressassem demandas sociais","baseada em sufrágio universal","aberta aos escravizados como deputados","inexistente nas províncias"],0,"A representação formal era limitada, mas não houve ausência total de mobilização popular."),
q("Os liberais moderados defendiam:",["limitar o imperador sem romper profundamente a ordem social","abolir imediatamente a monarquia e a escravidão","restaurar o domínio colonial","entregar o governo à Inglaterra"],0,"Seu liberalismo político convivia com a defesa da ordem escravista."),
q("A Noite da Agonia resultou:",["na dissolução da Assembleia, prisões e exílios","na aprovação do projeto pelos deputados","na abdicação imediata de D. Pedro","na proclamação da República"],0,"O imperador encerrou militarmente a Constituinte."),
q("Depois da dissolução, a nova Constituição foi elaborada por:",["um Conselho de Estado nomeado pelo imperador","uma assembleia eleita por voto universal","líderes populares da Bahia","representantes do governo português"],0,"Dez conselheiros prepararam o texto sob controle de D. Pedro."),
q("A Constituinte ocorreu enquanto:",["a consolidação militar da Independência ainda estava em curso","o Brasil já era uma República consolidada","Portugal havia abolido a monarquia","a escravidão havia terminado"],0,"As guerras regionais continuaram ao longo de 1823.")
]},
{id:"constituicao",title:"A ordem do Imperador",short:"Constituição de 1824",intro:"Poder Moderador, voto censitário, religião oficial e cidadania limitada.",accent:"#553e70",cover:A+"constituicao-pedro.png",pages:[
{t:"Outorgada de cima para baixo",img:A+"constituicao-pedro.png",cap:"Representação de D. Pedro I e da Constituição de 1824, oficializada em 25 de março.",text:"Após dissolver a Constituinte, D. Pedro encarregou um Conselho de Estado de redigir a Carta. A Constituição foi outorgada sem aprovação de representantes eleitos e permaneceu em vigor durante todo o Império.",concepts:[["Outorgada","Concedida pelo governante."],["Monarquia hereditária","D. Pedro e seus sucessores ocupavam a chefia do Estado."],["Centralização","Presidentes de província eram nomeados pelo imperador."]],exam:"Compare “promulgada” e “outorgada”: a primeira é aprovada por representantes; a segunda é imposta ou concedida pelo governante."},
{t:"O quarto poder",img:A+"charge-moderador.jpg",cap:"Charge sobre a concentração de poderes de D. Pedro I.",text:"Além de Executivo, Legislativo e Judiciário, a Carta criou o Poder Moderador, exclusivo do imperador. Ele podia dissolver a Câmara, nomear senadores, escolher ministros e presidentes de província e interferir nos demais poderes.",concepts:[["Poder Moderador","Instrumento de superioridade política do imperador."],["Senado vitalício","Senadores ocupavam o cargo por toda a vida e eram escolhidos pelo monarca em listas."],["Centralização","A autonomia provincial era reduzida."]],trap:"A existência de quatro poderes não significava maior equilíbrio; o Moderador ampliava a intervenção imperial."},
{t:"Direitos para poucos",img:A+"medalha-constituicao.png",cap:"Medalha de D. Pedro I e exemplar da Constituição de 1824.",text:"A Carta reconheceu alguns direitos individuais, mas manteve escravidão, voto censitário, religião católica oficial e participação política restrita. Escravizados não eram cidadãos, e até grande parte da população livre dependia de proprietários.",concepts:[["Voto censitário","Participação vinculada à renda."],["Religião oficial","Cultos não católicos eram permitidos apenas em espaços privados."],["Contradição liberal","Direitos formais coexistiam com escravidão e desigualdade."]],exam:"Vestibulares exploram a distância entre princípios liberais e práticas sociais escravistas."}],
questions:[
q("A Constituição de 1824 é classificada como outorgada porque:",["foi imposta pelo imperador sem aprovação de uma Constituinte eleita","foi aprovada por voto universal","resultou de plebiscito popular","foi redigida pelas províncias autônomas"],0,"A Carta foi concedida por D. Pedro I após a dissolução da Assembleia."),
q("O Poder Moderador permitia ao imperador:",["intervir nos demais poderes e dissolver a Câmara","apenas representar simbolicamente o Estado","ser eleito a cada quatro anos","abolir sozinho a escravidão"],0,"O quarto poder colocava o monarca acima da separação clássica."),
q("O voto estabelecido pela Constituição de 1824 era:",["censitário, condicionado por critérios de renda","universal e secreto","exclusivo para escravizados","direto para todos os cargos"],0,"A renda restringia diferentes etapas da participação eleitoral."),
q("Uma contradição da Carta de 1824 foi:",["reconhecer direitos liberais enquanto mantinha escravidão e exclusão","abolir a propriedade privada","eliminar a religião católica","garantir autonomia total às províncias"],0,"Princípios formais conviviam com uma sociedade escravista e hierárquica."),
q("Sobre religião, a Constituição:",["tornou o catolicismo oficial e restringiu cultos públicos de outras religiões","separou completamente Igreja e Estado","proibiu o catolicismo","garantiu igualdade pública irrestrita entre cultos"],0,"Outras crenças eram toleradas em espaços privados."),
q("A nomeação de presidentes de província pelo imperador reforçava:",["a centralização política do Império","o federalismo provincial","a soberania municipal","a participação popular direta"],0,"O governo central controlava as administrações provinciais.")
]}];

const BLOCKED=["palavrao","idiota","otario","otaria","burro","burra","merda","bosta","porra","caralho","puta","puto","fdp","cuzao","cuzona","desgraca","vagabundo","vagabunda"];
const state={name:"",className:"",attemptId:"",score:0,completed:{},scores:{},startedAt:0,current:null,questions:[],qIndex:0,currentScore:0};
const sound={enabled:true,ctx:null,ensure(){if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return false;this.ctx=new C()}if(this.ctx.state==="suspended")this.ctx.resume();return true},tone(f,d=.08,type="triangle",v=.025,delay=0){if(!this.enabled||!this.ensure())return;const n=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(v,n+.01);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g);g.connect(this.ctx.destination);o.start(n);o.stop(n+d+.03)},click(){this.tone(500,.05,"triangle",.014)},ok(){this.tone(523,.12);this.tone(659,.14,"triangle",.03,.07);this.tone(784,.18,"triangle",.03,.14)},bad(){this.tone(185,.16,"sawtooth",.02);this.tone(140,.2,"triangle",.025,.09)},async music(restart=false){if(!this.enabled)return;const a=document.getElementById("ambientMusic");a.volume=.1;if(restart)a.currentTime=0;try{await a.play();document.getElementById("soundBtn").textContent="ON"}catch(error){document.getElementById("soundBtn").textContent="PLAY"}},pause(){document.getElementById("ambientMusic").pause();document.getElementById("soundBtn").textContent=this.enabled?"SOM":"OFF"}};
function toggleSound(event){event?.stopPropagation();sound.enabled=!sound.enabled;if(sound.enabled){sound.click();sound.music()}else sound.pause()}
document.addEventListener("click",event=>{const b=event.target.closest("button,.btn");if(b&&b.id!=="soundBtn"&&!b.classList.contains("answer"))sound.click()});
function showOnly(id){["splash","register","app"].forEach(x=>document.getElementById(x).style.display=x===id?(x==="app"?"block":"flex"):"none")}
function showRegister(){sound.music(true);showOnly("register")}
function clean(v){return String(v||"").replace(/[<>]/g,"").replace(/\s+/g," ").trim().slice(0,40)}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function shuffle(items){const x=[...items];for(let i=x.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
async function validateName(value){const name=clean(value),key=norm(name);if(name.length<3)return{ok:false,message:"Digite um nome com pelo menos 3 letras. Nomes como Ana são aceitos."};if(BLOCKED.some(word=>key.includes(norm(word))))return{ok:false,message:"Esse nome não pode ser utilizado."};if(db)try{const s=await db.ref(`${DB_ROOT}/moderacao/nomesBloqueados/${key}`).once("value");if(s.exists())return{ok:false,message:"Esse nome foi bloqueado pelo professor."}}catch(error){}return{ok:true,name}}
async function startGame(){const warn=document.getElementById("warn"),raw=document.getElementById("name").value,turma=document.getElementById("class").value;if(!raw.trim()||!turma){warn.textContent="Digite seu nome e selecione a turma.";warn.style.display="block";return}warn.textContent="Verificando identificação...";warn.style.display="block";const result=await validateName(raw);if(!result.ok){warn.textContent=result.message;return}warn.style.display="none";Object.assign(state,{name:result.name,className:turma,attemptId:db?db.ref(`${DB_ROOT}/rankings/${GAME_ID}`).push().key:`local-${Date.now()}`,score:0,completed:{},scores:{},startedAt:Date.now()});showOnly("app");openMenu();registerGame()}
function level(s){if(s>=90)return"Curador-chefe";if(s>=70)return"Historiador do acervo";if(s>=50)return"Leitor de fontes";if(s>=25)return"Pesquisador";return"Visitante"}
function openMenu(){document.getElementById("menuView").style.display="block";document.getElementById("stageView").style.display="none";renderMenu();updateHud();scrollTo(0,0);sound.music()}
function renderMenu(){const count=Object.keys(state.completed).length;document.getElementById("progress").innerHTML=`${count*20}%<br>inaugurado`;document.getElementById("museumHall").innerHTML=GALLERIES.map((g,i)=>`<button class="gallery-door ${state.completed[g.id]?"done":""}" onclick="openGallery('${g.id}')"><img src="${g.cover}" alt=""><div class="door-copy"><small>GALERIA ${i+1} · 20 PONTOS</small><h2>${g.title}</h2><span>${g.intro}</span></div></button>`).join("")}
function updateHud(){document.getElementById("hudScore").textContent=state.score;document.getElementById("hudStages").textContent=`${Object.keys(state.completed).length}/5`;document.getElementById("hudLevel").textContent=level(state.score)}
function openGallery(id){const g=GALLERIES.find(x=>x.id===id);state.current=g;document.documentElement.style.setProperty("--accent",g.accent);document.getElementById("menuView").style.display="none";document.getElementById("stageView").style.display="block";document.getElementById("stageKicker").textContent=`Galeria ${GALLERIES.indexOf(g)+1} · 20 pontos`;document.getElementById("stageTitle").textContent=g.title;document.getElementById("stageIntro").textContent=g.intro;renderSources(g);state.questions=shuffle(g.questions).slice(0,4);state.qIndex=0;state.currentScore=0;document.getElementById("quizArea").classList.remove("hide");document.getElementById("complete").classList.add("hide");renderQuestion();scrollTo(0,0)}
function renderSources(g){document.getElementById("sourceNav").innerHTML=g.pages.map((p,i)=>`<button class="source-tab ${i?"":"active"}" onclick="selectSource(${i},this)">${i+1}. ${p.t}</button>`).join("");document.getElementById("sourcePages").innerHTML=g.pages.map((p,i)=>`<section class="source ${i?"":"active"}"><h2>${p.t}</h2><button class="source-image" onclick="openImage('${p.img}','${encodeURIComponent(p.t)}','${encodeURIComponent(p.cap)}')"><img src="${p.img}" alt="${esc(p.t)}"><span>CLIQUE PARA AMPLIAR</span></button><div class="caption">${p.cap}</div><p>${p.text}</p>${p.concepts?`<div class="concepts">${p.concepts.map(c=>`<div><b>${c[0]}</b>${c[1]}</div>`).join("")}</div>`:""}${p.exam?`<div class="exam"><b>Como isso cai na prova:</b> ${p.exam}</div>`:""}${p.trap?`<div class="trap"><b>Armadilha de alternativa:</b> ${p.trap}</div>`:""}</section>`).join("")}
function selectSource(i,b){document.querySelectorAll(".source-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".source").forEach((x,j)=>x.classList.toggle("active",i===j))}
function showSources(){document.querySelector(".collection").scrollIntoView({behavior:"smooth"})}
function renderQuestion(){const question=state.questions[state.qIndex],options=shuffle(question.ops.map((text,index)=>({text,correct:index===question.ok})));document.getElementById("qProgress").textContent=`QUESTÃO ${state.qIndex+1} DE 4 · ${state.currentScore} PONTOS`;document.getElementById("question").textContent=question.text;document.getElementById("answers").innerHTML=options.map(o=>`<button class="answer" onclick="answer(this,${o.correct})">${esc(o.text)}</button>`).join("");document.getElementById("feedback").className="feedback";document.getElementById("nextBtn").classList.add("hide")}
function answer(btn,correct){const question=state.questions[state.qIndex],buttons=[...document.querySelectorAll(".answer")];buttons.forEach(x=>x.disabled=true);if(correct){sound.ok();state.currentScore+=5;btn.classList.add("correct")}else{sound.bad();btn.classList.add("wrong");buttons.find(x=>x.textContent===question.ops[question.ok])?.classList.add("correct")}const f=document.getElementById("feedback");f.className=`feedback show ${correct?"ok":"bad"}`;f.innerHTML=`<b>${correct?"Resposta correta.":"Observe a alternativa destacada."}</b><br>${question.exp}`;const next=document.getElementById("nextBtn");next.textContent=state.qIndex===3?"Concluir galeria":"Próxima questão";next.classList.remove("hide")}
function nextQuestion(){if(state.qIndex<3){state.qIndex++;renderQuestion();return}document.getElementById("quizArea").classList.add("hide");document.getElementById("complete").classList.remove("hide");document.getElementById("stageScore").textContent=`${state.currentScore}/20`}
async function finishStage(){const id=state.current.id;if(!state.completed[id]){state.completed[id]=true;state.scores[id]=state.currentScore;state.score=Object.values(state.scores).reduce((a,b)=>a+b,0);await saveAttempt()}openMenu();if(Object.keys(state.completed).length===5){document.getElementById("finalScore").textContent=state.score;document.getElementById("finalLevel").textContent=level(state.score);document.getElementById("finalModal").classList.add("open")}}
async function registerGame(){if(!db)return;try{await db.ref(`${DB_ROOT}/jogos/${GAME_ID}`).update({titulo:GAME_TITLE,slug:GAME_ID,categoria:"História",ativo:true,pontuacaoMaxima:100,etapas:5,atualizadoEm:firebase.database.ServerValue.TIMESTAMP})}catch(error){}}
async function saveAttempt(){const now=new Date(),record={nome:state.name,turma:state.className,pontos:state.score,nivel:level(state.score),data:now.toLocaleString("pt-BR"),jogoId:GAME_ID,jogoTitulo:GAME_TITLE,nomeNormalizado:norm(state.name),visivel:true,etapasConcluidas:Object.keys(state.completed),quantidadeEtapas:Object.keys(state.completed).length,pontuacaoPorEtapa:state.scores,duracaoSegundos:Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),criadoEm:state.startedAt,atualizadoEm:db?firebase.database.ServerValue.TIMESTAMP:Date.now()};if(db)try{await db.ref(`${DB_ROOT}/rankings/${GAME_ID}/${state.attemptId}`).set(record);return}catch(error){}const key=`${GAME_ID}-ranking`,list=JSON.parse(localStorage.getItem(key)||"[]"),i=list.findIndex(x=>x.id===state.attemptId),local={id:state.attemptId,...record,atualizadoEm:Date.now()};if(i>=0)list[i]=local;else list.push(local);localStorage.setItem(key,JSON.stringify(list))}
async function loadRanking(){if(db)try{const [r,b]=await Promise.all([db.ref(`${DB_ROOT}/rankings/${GAME_ID}`).once("value"),db.ref(`${DB_ROOT}/moderacao/nomesBloqueados`).once("value")]),rows=[],blocked=b.val()||{};r.forEach(c=>{const v=c.val();if(v.visivel!==false&&!blocked[norm(v.nome)])rows.push({id:c.key,...v})});return rows}catch(error){}try{return JSON.parse(localStorage.getItem(`${GAME_ID}-ranking`)||"[]")}catch(error){return[]}}
async function openRanking(){document.getElementById("rankingModal").classList.add("open");const box=document.getElementById("rankingContent");box.innerHTML='<div style="padding:22px;text-align:center">Carregando...</div>';const rows=(await loadRanking()).sort((a,b)=>(b.pontos||0)-(a.pontos||0)||(b.quantidadeEtapas||0)-(a.quantidadeEtapas||0)||(a.duracaoSegundos||1e9)-(b.duracaoSegundos||1e9));box.innerHTML=rows.length?`<table><thead><tr><th>#</th><th>Estudante</th><th>Turma</th><th>Pontos</th><th>Galerias</th><th>Nível</th><th>Data</th></tr></thead><tbody>${rows.slice(0,200).map((r,i)=>`<tr class="${r.id===state.attemptId?"me":""}"><td>${i+1}</td><td>${esc(r.nome)}</td><td>${esc(r.turma)}</td><td><b>${r.pontos||0}</b></td><td>${r.quantidadeEtapas||0}/5</td><td>${esc(r.nivel||"")}</td><td>${esc(r.data||"")}</td></tr>`).join("")}</tbody></table>`:"<div style='padding:22px'>Nenhuma tentativa registrada.</div>"}
function openGuide(){document.getElementById("guideModal").classList.add("open")}
function openImage(src,title,cap){document.getElementById("lightboxImage").src=src;document.getElementById("lightboxTitle").textContent=decodeURIComponent(title);document.getElementById("lightboxCaption").textContent=decodeURIComponent(cap);document.getElementById("imageModal").classList.add("open")}
function closeModal(id){document.getElementById(id).classList.remove("open")}
showOnly("splash");
