function q(text,ops,ok,exp){return{text,ops,ok,exp}}
const STAGES=[
{id:"conceito",title:"Renascimento em debate",intro:"Continuidades, mudanças e os limites da ideia de Idade das Trevas.",max:15,pages:[
{t:"Duas estéticas",img:"assets/arte-medieval.png",cap:"Cristo lavando os pés dos apóstolos, Evangelhos de Otto III, século X.",text:"A arte medieval valorizava convenções simbólicas próprias. Compará-la à arte renascentista não autoriza classificá-la como inferior: cada imagem responde a finalidades e concepções de mundo distintas.",concepts:[["Fonte histórica","A forma visual expressa valores de seu contexto."],["Anacronismo","Julgar outra época apenas por padrões atuais."],["Teocentrismo","Centralidade religiosa não significa ausência de razão ou cultura."]]},
{t:"Ruptura ou continuidade?",img:"assets/madona-rafael.jpg",cap:"Madona e Criança, Rafael, século XVI.",text:"O nome Renascimento foi construído a partir da valorização da Antiguidade clássica e ajudou a criar a imagem de uma Idade Média obscura. Pesquisas atuais destacam permanências: saberes antigos circularam durante o período medieval e temas cristãos continuaram centrais na arte renascentista.",concepts:[["Renascimento","Movimento cultural dos séculos XIV a XVI."],["Classicismo","Releitura de modelos greco-romanos."],["Continuidade","Mudanças históricas preservam e reelaboram elementos anteriores."]],strategy:"Alternativas que apresentam ruptura total, superioridade automática ou desaparecimento da religião costumam simplificar o processo."}],
questions:[
q("O conceito de Renascimento refere-se principalmente a um movimento que:",["eliminou a cultura religiosa europeia","releu referências clássicas pelo humanismo","restaurou integralmente a sociedade romana","substituiu cidades por estruturas feudais"],1,"A questão contextualiza o movimento sem tratá-lo como cópia da Antiguidade."),
q("A crítica à expressão Idade das Trevas sustenta que:",["a Idade Média não conheceu conflitos políticos","o saber clássico desapareceu até o século XV","houve continuidades culturais entre períodos históricos","a arte medieval adotava perspectiva científica"],2,"A historiografia atual questiona a ideia de vazio cultural medieval."),
q("A comparação entre as duas imagens deve evitar a conclusão de que:",["estéticas distintas expressam diferentes valores","a pintura renascentista é objetivamente superior","obras religiosas podem revelar mudanças culturais","fontes visuais exigem contextualização"],1,"Diferença estética não estabelece uma escala universal de qualidade."),
q("A presença de temas cristãos em obras renascentistas indica que:",["humanismo e religiosidade podiam coexistir","o antropocentrismo restaurou o paganismo","o Renascimento rejeitou a arte clássica","a Igreja perdeu toda influência cultural"],0,"A valorização humana não significou abandono da religião."),
q("O termo Renascimento também deve ser analisado criticamente porque:",["é uma categoria histórica construída","designa apenas invenções científicas produzidas em Florença","foi usado pelos medievais para definir sua própria cultura","comprova que toda transformação histórica é repentina"],0,"Periodizações são construções interpretativas, não divisões naturais do tempo.")
]},
{id:"humanismo",title:"O ser humano em foco",intro:"Humanismo, individualismo, antropocentrismo, autoria e dignidade.",max:15,pages:[
{t:"Autoria e individualidade",img:"assets/pieta.jpg",cap:"Pietà, Michelangelo, 1498-1499. O artista gravou sua assinatura na faixa sobre o peito de Maria.",text:"A assinatura evidencia a crescente valorização social do artista como criador individual. Isso não significa que artistas medievais fossem incapazes ou sempre anônimos, mas aponta mudanças no prestígio da autoria.",concepts:[["Individualismo","Valorização da identidade e da capacidade individual."],["Artista intelectual","Reconhecimento além do trabalho artesanal."],["Autoria","Relaciona obra, reputação e mercado cultural."]]},
{t:"Medida e dignidade",img:"assets/vitruviano.jpg",cap:"O Homem Vitruviano, Leonardo da Vinci, c. 1492.",text:"Leonardo relacionou anatomia, proporção, arte e matemática. Pico della Mirandola exaltou a capacidade humana de aprender e transformar-se. O antropocentrismo deslocava o foco para a experiência humana sem afirmar que Deus deixou de existir.",concepts:[["Humanismo","Estudo do humano, das letras e da cultura clássica."],["Antropocentrismo","Ser humano como referência para conhecer e agir."],["Racionalismo","Confiança na razão e na investigação."]],strategy:"Não confunda antropocentrismo com ateísmo nem individualismo com egoísmo moderno."}],
questions:[
q("No Renascimento, o humanismo valorizava:",["razão, ação humana e estudos clássicos","a proibição das línguas vernáculas","o anonimato obrigatório dos artistas","a recusa de toda tradição antiga"],0,"A questão contextualiza o humanismo."),
q("A assinatura de Michelangelo na Pietà pode ser relacionada:",["ao desaparecimento do mecenato religioso","à valorização da autoria e do prestígio individual","à rejeição renascentista das esculturas","ao controle das obras pelas corporações medievais"],1,"A assinatura participa da nova posição social atribuída ao artista."),
q("O Homem Vitruviano articula arte e conhecimento ao:",["relacionar corpo e proporção geométrica","provar que o corpo ideal existia em todos os indivíduos","subordinar a anatomia apenas a símbolos religiosos","negar a influência dos autores antigos"],0,"A obra combina observação, matemática e referência clássica."),
q("O antropocentrismo renascentista não deve ser entendido como:",["valorização da capacidade humana de conhecer","interesse pelo corpo e pela experiência","abandono completo da religiosidade cristã","confiança na ação criativa dos indivíduos"],2,"Humanismo e cristianismo coexistiram em muitas obras e autores."),
q("A mudança na imagem social do artista ocorreu quando ele passou a ser visto também como:",["intelectual capaz de elaborar soluções e ideias","funcionário anônimo sem reconhecimento público","copista limitado a repetir modelos impostos","opositor necessário de todo patrocinador religioso"],0,"Artistas ganharam reconhecimento como autores e inventores.")
]},
{id:"linguagem",title:"A construção do olhar",intro:"Perspectiva, anatomia, luz, proporção e representação das emoções.",max:15,pages:[
{t:"Perspectiva e razão",img:"assets/escola-atenas.jpg",cap:"A Escola de Atenas, Rafael, 1509-1510.",text:"A perspectiva linear organiza o espaço a partir de um ponto de fuga. Em A Escola de Atenas, arquitetura clássica, simetria e filósofos antigos constroem uma celebração visual da razão e do conhecimento.",concepts:[["Perspectiva","Sistema geométrico para representar profundidade."],["Simetria","Organização equilibrada da composição."],["Classicismo","Arquitetura e personagens retomam a Antiguidade."]]},
{t:"Corpo e emoção",img:"assets/ultima-ceia.jpg",cap:"A Última Ceia, Leonardo da Vinci, 1494-1498.",text:"Leonardo organizou a cena com Cristo no ponto de fuga e diferenciou as reações dos apóstolos. Anatomia, gestos, luz e composição produzem profundidade e dramatização psicológica.",concepts:[["Ponto de fuga","Convergência das linhas de perspectiva."],["Chiaroscuro","Contrastes de luz e sombra criam volume."],["Expressividade","Gestos e rostos comunicam reações individuais."]],strategy:"Ao analisar uma obra, relacione técnica e significado; não apenas liste elementos visuais."}],
questions:[
q("A perspectiva linear nas pinturas renascentistas permitia:",["construir profundidade geometricamente","eliminar personagens humanos das cenas","abandonar qualquer observação da natureza","transformar toda pintura em mapa científico"],0,"A questão contextualiza a técnica da perspectiva."),
q("Em A Escola de Atenas, a reunião de filósofos antigos sugere:",["rejeição do conhecimento racional","valorização humanista da tradição clássica","condenação da arquitetura greco-romana","separação completa entre arte e filosofia"],1,"A obra transforma referências antigas em programa cultural renascentista."),
q("Na Última Ceia, o ponto de fuga concentrado em Cristo:",["organiza o espaço e reforça o centro narrativo","demonstra desprezo pela geometria","elimina a dimensão religiosa da obra","torna idênticas as reações dos apóstolos"],0,"A solução técnica também orienta a leitura do acontecimento."),
q("O estudo anatômico contribuía para:",["corpos mais proporcionais e movimentos convincentes","a proibição de representar figuras religiosas","o retorno às formas planas da pintura medieval","a substituição da arte pela medicina"],0,"Conhecimentos do corpo apoiavam novas soluções visuais."),
q("Luz, gestos e expressões são fontes históricas quando:",["ajudam a interpretar valores e escolhas do artista","reproduzem objetivamente todos os acontecimentos","dispensam informações sobre contexto e autoria","garantem uma única interpretação correta"],0,"Elementos formais precisam ser contextualizados e argumentados.")
]},
{id:"beleza",title:"Beleza e mundos clássicos",intro:"Mitologia, idealização, natureza e transformações históricas do belo.",max:15,pages:[
{t:"O nascimento de Vênus",img:"assets/venus.jpg",cap:"O Nascimento de Vênus, Sandro Botticelli, 1485.",text:"A deusa clássica ocupa o centro da pintura. Mitologia, corpo idealizado, natureza e equilíbrio indicam a releitura renascentista da Antiguidade. O belo não é universal: cada sociedade constrói padrões e sentidos.",concepts:[["Mitologia","Temas antigos retornam em novos contextos."],["Idealização","A representação seleciona e aperfeiçoa formas."],["Belo histórico","Padrões estéticos variam no tempo e entre culturas."]]},
{t:"Baco e Ariadne",img:"assets/baco-ariadne.jpg",cap:"Baco e Ariadne, Ticiano, 1520-1523.",text:"Cor, movimento, emoções e narrativa mitológica mostram outra possibilidade renascentista, ligada à cultura das elites e ao patrocínio artístico. O resgate clássico não era simples imitação.",concepts:[["Reapropriação","O passado é selecionado e reinterpretado."],["Mecenato","Encomendas influenciam temas e circulação."],["Natureza","Paisagem e movimento integram a narrativa."]],strategy:"Em questões de arte, procure a alternativa que explica o que a escolha mitológica revela sobre a sociedade produtora."}],
questions:[
q("A mitologia greco-romana nas obras renascentistas evidencia:",["releitura da cultura clássica em novos contextos","abandono de toda produção cristã","restauração das religiões antigas como oficiais","recusa do estudo da natureza"],0,"A questão contextualiza o classicismo."),
q("O corpo de Vênus pode ser entendido como idealizado porque:",["segue escolhas estéticas de proporção e beleza","é uma fotografia fiel de uma personagem histórica","rejeita qualquer convenção cultural do período","representa o padrão corporal de toda a população"],0,"Idealização é construção artística, não retrato social universal."),
q("Comparar concepções de belo ao longo do tempo permite concluir que:",["os padrões estéticos possuem dimensão histórica","a beleza renascentista é naturalmente superior","todas as sociedades adotam os mesmos critérios","a arte medieval não possuía conceito de beleza"],0,"O belo varia com valores, práticas e contextos."),
q("A presença de temas pagãos em obras financiadas por elites cristãs demonstra:",["circulação e ressignificação de referências clássicas","fim imediato da influência religiosa na arte","incompatibilidade absoluta entre cristianismo e humanismo","domínio político das antigas cidades gregas"],0,"Referências pagãs podiam integrar repertórios de sociedades cristãs."),
q("Baco e Ariadne revela a relação entre arte e sociedade ao expressar:",["gostos eruditos e circuitos de encomenda das elites","uma cena cotidiana documentada sem elaboração","rejeição veneziana ao uso das cores","ausência de interesse por emoções humanas"],0,"O tema e a linguagem dialogam com públicos e patronos específicos.")
]},
{id:"circulacao",title:"Cidade, mecenas e circulação",intro:"Florença, burguesia, patrocínio, imprensa e transformação do acesso ao saber.",max:15,pages:[
{t:"A cidade como laboratório",img:"assets/florenca.jpg",cap:"Catedral de Santa Maria del Fiore, Florença; cúpula projetada por Brunelleschi.",text:"Comércio, bancos e disputas urbanas favoreceram redes de encomenda. Famílias como os Médici financiavam obras para produzir prestígio, devoção e poder. Mecenas não eram apenas admiradores desinteressados.",concepts:[["Mecenato","Patrocínio de artistas e intelectuais."],["Burguesia","Grupos urbanos ligados ao comércio e às finanças."],["Prestígio","Obras comunicavam riqueza, fé e autoridade."]]},
{t:"A prensa",img:"assets/prensa.png",cap:"Prensa de impressão representada em catálogo de 1830.",text:"Os tipos móveis reduziram tempo e custo de reprodução dos textos e ampliaram sua circulação. A transformação foi profunda, mas não criou acesso universal: livros, alfabetização e censura continuaram desiguais.",concepts:[["Imprensa","Multiplicação mais rápida de cópias."],["Circulação","Ideias alcançaram redes geográficas maiores."],["Limite","Ampliação não significa democratização imediata."]],strategy:"Relacione tecnologia, agentes sociais e limites; evite determinismo tecnológico."}],
questions:[
q("O mecenato renascentista consistia no:",["patrocínio artístico ligado ao prestígio","trabalho artístico sem encomendas ou remuneração","controle exclusivo das obras pelas universidades","abandono da produção religiosa nas cidades"],0,"A questão contextualiza o patrocínio."),
q("O crescimento urbano favoreceu o Renascimento porque:",["ampliou redes de riqueza, encomenda e circulação cultural","eliminou as diferenças sociais entre os habitantes","encerrou os vínculos entre arte e instituições religiosas","isolou os artistas das atividades comerciais"],0,"As cidades reuniam recursos, públicos e disputas simbólicas."),
q("Uma obra financiada pelos Médici deve ser analisada considerando:",["os interesses de prestígio e poder do patrocinador","apenas a inspiração individual do artista","a ausência de relações entre cultura e política","a neutralidade social de toda encomenda"],0,"Patrocínio e finalidade influenciam produção e circulação."),
q("A prensa de tipos móveis transformou a cultura escrita ao:",["acelerar a reprodução e circulação dos textos","alfabetizar imediatamente todos os europeus","eliminar manuscritos no mesmo momento","impedir governantes de exercer censura"],0,"A imprensa ampliou escalas sem universalizar o acesso."),
q("Comparar a prensa ao computador destaca principalmente:",["mudanças na circulação da informação","igualdade completa entre os contextos históricos","desaparecimento do livro em ambos os períodos","criação de conhecimento sem participação humana"],0,"A comparação trata do impacto comunicacional, não de identidade histórica.")
]},
{id:"ciencia",title:"A natureza em investigação",intro:"Método, observação, experimentação, heliocentrismo e autoridade.",max:25,pages:[
{t:"Métodos em construção",img:"assets/metodo-cientifico.jpg",cap:"Esquema didático das etapas do método científico.",text:"Bacon valorizou observação e indução; Descartes, razão e dedução. A Revolução Científica não criou um método único de uma vez, mas consolidou práticas de teste, cálculo, crítica e comunicação.",concepts:[["Empirismo","Conhecimento apoiado na experiência."],["Racionalismo","Uso sistemático da razão."],["Método","Procedimentos controláveis para produzir conhecimento."]]},
{t:"Dois modelos de universo",img:"assets/heliocentrismo.jpg",cap:"Representação do modelo heliocêntrico de Copérnico.",text:"O heliocentrismo deslocou a Terra do centro do modelo astronômico. Galileu utilizou observações telescópicas e experimentos em conflitos que também envolviam instituições, interpretações bíblicas e autoridades acadêmicas.",concepts:[["Heliocentrismo","Planetas orbitam o Sol."],["Geocentrismo","Terra ocupa o centro do modelo."],["Autoridade","Novas evidências desafiaram saberes estabelecidos."]],strategy:"A Revolução Científica não foi uma guerra simples entre ciência e religião; houve cientistas religiosos, disputas internas e mudanças graduais."}],
questions:[
q("A Revolução Científica valorizou especialmente:",["observação, cálculo, experimentação e crítica","repetição de autoridades sem verificação","abandono da matemática na investigação","negação de qualquer hipótese sobre a natureza"],0,"A questão contextualiza práticas científicas modernas."),
q("Bacon e Descartes são frequentemente associados, respectivamente:",["à indução empírica e à dedução racional","ao geocentrismo e à astrologia medieval","à pintura e à escultura clássica","ao mecenato e à imprensa"],0,"Os autores enfatizaram caminhos metodológicos diferentes."),
q("O heliocentrismo representou uma transformação porque:",["reorganizou o modelo astronômico em torno do Sol","provou que o universo não possuía leis","eliminou imediatamente o geocentrismo europeu","foi formulado apenas após o telescópio de Galileu"],0,"Copérnico propôs novo arranjo para os movimentos celestes."),
q("Os experimentos atribuídos a Galileu contrariavam Aristóteles ao:",["submeter afirmações sobre movimento a testes e medidas","confirmar que objetos pesados sempre caem muito antes","rejeitar o uso da matemática em fenômenos físicos","substituir observações por argumentos de autoridade"],0,"A experiência e a matematização permitiam rever teses consagradas."),
q("O conflito entre novas teorias e saberes estabelecidos deve ser explicado:",["por disputas de evidência, interpretação e autoridade","como oposição inevitável entre toda fé e toda ciência","pela ausência completa de religiosos entre cientistas","apenas pelo desconhecimento da imprensa"],0,"O processo envolveu instituições e agentes diversos."),
q("A ideia de método científico não autoriza concluir que:",["existiu um único procedimento científico","hipóteses podem ser confrontadas com evidências","resultados devem ser analisados e comunicados","razão e experiência participaram da investigação"],0,"Métodos científicos foram plurais e historicamente construídos."),
q("Arte e ciência renascentistas aproximaram-se em práticas como:",["estudo anatômico, proporção, perspectiva e observação","rejeição do corpo humano como objeto de estudo","abandono de referências matemáticas nas pinturas","separação total entre artistas e investigadores"],0,"Artistas e estudiosos compartilharam problemas, técnicas e curiosidade."),
q("Uma interpretação historicamente adequada do Renascimento reconhece:",["novidades combinadas a permanências históricas","ruptura completa e instantânea com o passado","superioridade natural da cultura italiana","desaparecimento da religião na vida intelectual"],0,"Transformações históricas reelaboram heranças e produzem novidades.")
]}];
